name: Go

on:
  push:
    branches:    
      - main
    tags:
      - v*

jobs:

  windows:
    name: Build for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
    
    - name: Build
      run: make windows
        
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_build
        path: |
          bin/go-java-launcher_windows.exe
          go-java.json
    
  linux:
    name: Build for linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
      
    - name: Build
      run: make linux
        
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: |
          bin/go-java-launcher_linux
          go-java.json
