name: Go

on:
  push:
    branches: [ main ]

jobs:

  windows:
    name: Build for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build
        rsrc -ico icon.ico
        go build -ldflags -H=windowsgui
        
    
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows_build
        path: ./go-java-launcher.exe
